#!/bin/sh

SRC_DIR="."
export PATH="$PATH:$(go env GOPATH)/bin"

targets=( "miner-module" "coordinator-module" )


for target in "${targets[@]}"; do
    echo "compiling for target: $target"
    targetPath="../apps/$target/proto"

    # rm -rf "$targetPath"/*

    protoc --proto_path="$SRC_DIR" \
           --go_out="$targetPath" --go_opt=paths=source_relative \
           --go-grpc_out="$targetPath" --go-grpc_opt=paths=source_relative \
            $SRC_DIR/*.proto
done


