version: '3'

services:
  commander-module:
    image: 'm4schini/metron-commander'
    build:
      context: ./commander-module
    depends_on:
      - coordinator-module
      - redis
      - database
    environment:
      - EVENT_BUS_ADDR=redis:6379
      - METRON_DB_HOST=database
      - METRON_DB_PORT=3306
      - METRON_DB_PASS=$DB_MAIN_PW
      - METRON_DB_USER=root
      - METRON_DB_NAME=tiktok
  coordinator-module:
    image: 'm4schini/metron-coordinator'
    build:
      context: ./coordinator-module
    depends_on:
      - redis
    environment:
      - ADDR=:30051
      - EVENT_BUS_ADDR=redis:6379
      - EVENT_BUS_PASSWORD=
    ports:
      - "30051:30051"
  #miner-module:
  #  image: 'm4schini/metron-miner'
  #  build:
  #    context: ./miner-module
  #  depends_on:
  #    - coordinator-module
  #    - tor-proxy
  #  environment:
  #    - ADDR=miner-module:30051
  #    - COORDINATOR_ADDR=coordinator-module:30051

  database:
    image: 'docker.io/library/mariadb:10.3'
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: $DB_TEST_PW
      MYSQL_ROOT_PASSWORD: $DB_MAIN_PW
    healthcheck:
      test: "/usr/bin/mysql --user=test --password=$DB_TEST_PW --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    volumes:
      - "./database/tiktok-init.sql:/docker-entrypoint-initdb.d/1.sql"
  redis:
    image: 'redis:latest'
    hostname: redis
    ports:
      - "6379:6379"
  #tor-proxy:
  #  image: 'pickapp/tor-proxy'
  #  environment:
  #    - IP_CHANGE_INTERVAL=180
  #  ports:
  #    - '8888:8888'