version: '3.9'

services:
  coordinator-module:
    image: 'm4schini/metron-coordinator'
    build:
      context: ./coordinator-module
    environment:
      - ADDR=:30051
    ports:
      - "30051:30051"
  miner-module-1:
    image: 'm4schini/metron-miner'
    build:
      context: ./miner-module
    depends_on:
      - coordinator-module
    environment:
      - ADDR=miner-module-1:30051
      - COORDINATOR_ADDR=coordinator-module:30051
  miner-module-2:
    image: 'm4schini/metron-miner'
    build:
      context: ./miner-module
    depends_on:
      - coordinator-module
    environment:
      - ADDR=miner-module-2:30051
      - COORDINATOR_ADDR=coordinator-module:30051
  miner-module-3:
    image: 'm4schini/metron-miner'
    build:
      context: ./miner-module
    depends_on:
      - coordinator-module
    environment:
      - ADDR=miner-module-3:30051
      - COORDINATOR_ADDR=coordinator-module:30051
